# Aston Hack 
# 
# 

version: '3.3'

services:
   compileService:
     image: ro5635/astonhacksitebuildenv
     tty: true
     volumes:
       - ./:/codeSource

   webServer:
     ports: 
       - "85:80"
     image: nginx
     volumes:
        - ./static:/usr/share/nginx/html:ro
